import 'jquery';
import 'jquery-ui';
import '../../assets/libs/gantt/jquery/jquery.livequery.1.1.1.min';
import '../../assets/libs/gantt/jquery/jquery.timers';
import '../../assets/libs/gantt/utilities';
import '../../assets/libs/gantt/forms';
import '../../assets/libs/gantt/date';
import '../../assets/libs/gantt/dialogs';
import '../../assets/libs/gantt/layout';
import '../../assets/libs/gantt/i18nJs';
import '../../assets/libs/gantt/jquery/dateField/jquery.dateField';
import '../../assets/libs/gantt/jquery/JST/jquery.JST';
import '../../assets/libs/gantt/jquery/valueSlider/jquery.mb.slider';
import '../../assets/libs/gantt/jquery/svg/jquery.svg.min';
import '../../assets/libs/gantt/jquery/svg/jquery.svgdom.1.8';
import '../../assets/js/gantt/ganttUtilities';
import '../../assets/js/gantt/ganttTask';
// import '../../assets/js/gantt/ganttDrawerSVG';
// import '../../assets/js/gantt/ganttZoom';
import '../../assets/js/gantt/ganttGridEditor';
import '../../assets/js/gantt/ganttMaster';
// import '../../assets/js/gantt/ganttTestSuite';
import '../../assets/css/gantt/gantt.css';
import '../../assets/css/gantt/ganttPrint.css';
import '../../assets/css/gantt/platform.css';
import './index.scss';
import './index.html';
